<a href="https://colab.research.google.com/github/jewelry715/github_test/blob/master/Hello%EB%A5%BC_RNN%EC%9C%BC%EB%A1%9C_%EC%B6%9C%EB%A0%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
char_rdic=['h','e','l','o'] #id를 char로 변환
char_dic={w:i for i,w in enumerate(char_rdic)}
ground_truth=[char_dic[c] for c in 'hello']

In [ ]:
x_data=np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,1,0]],dtype='f') #h,e,1,1

In [ ]:
print('char dic : ',char_dic) #char를 id로 변환
print('ground truth \ "Hello\" : ',ground_truth)

char dic :  {'h': 0, 'e': 1, 'l': 2, 'o': 3}
ground truth \ "Hello" :  [0, 1, 2, 2, 3]


In [ ]:
x_data=tf.one_hot(ground_truth[:-1],len(char_dic),1.0,0.0,-1) #[0,1,2,2],depth,해당위치,axis=-1
print('x_data : ',x_data)

x_data :  Tensor("one_hot:0", shape=(4, 4), dtype=float32)


In [ ]:
rnn_size=len(char_dic) #4
batch_size=1
output_size=4
rnn_cell=tf.nn.rnn_cell.BasicRNNCell(num_units=rnn_size) #셀 내부의 unit의 개수로 아웃풋과 관계가 있다
initial_state=rnn_cell.zero_state(batch_size,tf.float32)
initial_state_1=tf.zeros([batch_size,rnn_cell.state_size])

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [ ]:
x_split=tf.split(x_data,len(char_dic),0) #가로축으로 4개로 split,(4,4)->(1,4)
print('x_split : ',x_split)
outputs,state=tf.contrib.rnn.static_rnn(cell=rnn_cell,inputs=x_split,initial_state=initial_state)
print('outputs : ',outputs)
print('state : ',state)

x_split :  [<tf.Tensor 'split:0' shape=(1, 4) dtype=float32>, <tf.Tensor 'split:1' shape=(1, 4) dtype=float32>, <tf.Tensor 'split:2' shape=(1, 4) dtype=float32>, <tf.Tensor 'split:3' shape=(1, 4) dtype=float32>]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
outputs :  [<tf.Tensor 'rnn/basic_rnn_cell/Tanh:0' shape=(1, 4) dtype=float32>, <tf.Tensor 'rnn/basic_rnn_cell/Tanh_1:0' sha

In [ ]:
logits=tf.reshape(tf.concat(outputs,1),[-1,rnn_size]) #1X16->4X4
logits.get_shape()

TensorShape([Dimension(4), Dimension(4)])

In [ ]:
targets=tf.reshape(ground_truth[1:],[-1])
targets.get_shape()

TensorShape([Dimension(4)])

In [ ]:
weights=tf.ones([len(char_dic)*batch_size])
loss=tf.contrib.legacy_seq2seq.sequence_loss_by_example([logits],[targets],[weights]) #예측,실제,반영비율
cost=tf.reduce_sum(loss)/batch_size
train_op=tf.train.RMSPropOptimizer(0.01,0.9).minimize(cost)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [ ]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
for i in range(100):
  sess.run(train_op,)
  result=sess.run(tf.argmax(logits,axis=1))
  print(result,[char_rdic[t] for t in result])

[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 3 0 3] ['h', 'o', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 0 3] ['h', 'l', 'h', 'o']
[0 2 3 3] ['h', 'l', 'o', 'o']
[0 2 3 3] ['h', 'l', 'o', 'o']
[0 2 3 3] ['h', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3